services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: yarn dev
        volumes:
            - ./:/app/
            - /app/node_modules
        ports:
            - 3000:3000
